services:
  nodered:
    build: ../../code/nodered-edge
    container_name: iot-edge-nodered
    networks:
      - iot-edge-network
    ports:
      - "1881:1881"
    volumes:
      - nodered-data:/data
    environment:
      - TZ=Europe/London
      - PORT=1881
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: iot-edge-ollama
    networks:
      - iot-edge-network
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    env_file:
      - .env
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_NO_GPU=1

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: iot-edge-mqtt-broker
    networks:
      - iot-edge-network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../../code/mosquitto/config:/mosquitto/config
      - ../../code/mosquitto/data:/mosquitto/data
      - ../../code/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: iot-edge-redis
    networks:
      - iot-edge-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

  edge-dashboard:
    build:
      context: ../../code/edge-dashboard
      dockerfile: Dockerfile
    container_name: iot-edge-dashboard
    depends_on:
      - redis
      - ollama
    environment:
      - FORCE_COLOR=1
    env_file:
      - .env
    networks:
      - iot-edge-network
    ports:
      - "4000:4000"
    restart: unless-stopped

networks:
  iot-edge-network:
    name: iot-edge-network
    driver: bridge

volumes:
  redis-data:
  nodered-data:
  ollama-data:
